'use client';

import { useState } from 'react';
import { jsPDF } from 'jspdf';

interface SOAPNote {
  subjective: string;
  objective: string;
  assessment: string;
  plan: string;
}

interface ExportPDFButtonProps {
  clientName: string;
  sessionDate: string;
  soapNote: SOAPNote;
}

export function ExportPDFButton({ clientName, sessionDate, soapNote }: ExportPDFButtonProps) {
  const [exporting, setExporting] = useState(false);

  const handleExport = async () => {
    setExporting(true);

    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;
      const maxWidth = pageWidth - margin * 2;
      let y = 20;

      // Header
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text('SOAP Notes', margin, y);
      y += 10;

      // Client & Date
      doc.setFontSize(12);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100);
      doc.text(`Client: ${clientName}`, margin, y);
      y += 6;
      doc.text(`Date: ${new Date(sessionDate).toLocaleDateString('en-US', {
        weekday: 'long',
        month: 'long',
        day: 'numeric',
        year: 'numeric',
      })}`, margin, y);
      y += 15;

      doc.setTextColor(0);

      // Helper to add section with word wrap
      const addSection = (title: string, content: string) => {
        // Check if we need a new page
        if (y > 250) {
          doc.addPage();
          y = 20;
        }

        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text(title, margin, y);
        y += 8;

        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');

        const lines = doc.splitTextToSize(content || 'N/A', maxWidth);
        lines.forEach((line: string) => {
          if (y > 280) {
            doc.addPage();
            y = 20;
          }
          doc.text(line, margin, y);
          y += 6;
        });
        y += 8;
      };

      // SOAP Sections
      addSection('Subjective', soapNote.subjective);
      addSection('Objective', soapNote.objective);
      addSection('Assessment', soapNote.assessment);
      addSection('Plan', soapNote.plan);

      // Footer
      doc.setFontSize(9);
      doc.setTextColor(150);
      doc.text(
        `Generated by SOAP Voice - ${new Date().toLocaleDateString()}`,
        margin,
        doc.internal.pageSize.getHeight() - 10
      );

      // Save
      const fileName = `SOAP_${clientName.replace(/\s+/g, '_')}_${new Date(sessionDate).toISOString().split('T')[0]}.pdf`;
      doc.save(fileName);
    } catch (error) {
      console.error('PDF export error:', error);
      alert('Failed to export PDF');
    } finally {
      setExporting(false);
    }
  };

  return (
    <button
      onClick={handleExport}
      disabled={exporting}
      className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg font-medium hover:bg-green-700 transition-colors disabled:opacity-50 min-h-[44px]"
    >
      <DownloadIcon className="w-5 h-5" />
      {exporting ? 'Exporting...' : 'Export PDF'}
    </button>
  );
}

function DownloadIcon({ className }: { className?: string }) {
  return (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
    </svg>
  );
}
